name = "am-prime-construction"
main = "./.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./.output/public"
binding = "ASSETS"

[[send_email]]
name = "SEND_EMAIL"
destination_address = "contact@am-prime-construction.co.uk"
